'use client';

import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Radar, RefreshCw, Loader2, Sparkles, TrendingUp, History } from 'lucide-react';

import { AppShell } from '@/components/app/app-shell';
import { PageHeader, SectionCard, EmptyState, Disclaimer } from '@/components/app/ui';
import { Button } from '@/components/ui/button';
import { useFarm } from '@/components/providers/farm-provider';
import { supabase } from '@/lib/supabase';

type TwinResult = {
  current_state: string;
  projection: string;
  pattern_insights: string[];
};

export default function FarmTwinPage() {
  return <AppShell><FarmTwinContent /></AppShell>;
}

function FarmTwinContent() {
  const { activeFarm } = useFarm();
  const [twin, setTwin] = useState<TwinResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);

  const generateTwin = async () => {
    if (!activeFarm) return;
    setLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('farm-twin', {
        body: { farmId: activeFarm.id },
      });
      if (error) throw error;
      setTwin(data as TwinResult);
      setGeneratedAt(new Date());
    } catch (err) {
      toast.error('Could not generate farm twin. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (activeFarm) generateTwin();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeFarm]);

  return (
    <div className="mx-auto max-w-4xl">
      <PageHeader
        title="Farm Twin"
        description="A living, personalized model of your farm — built from your own data"
        icon={Radar}
        action={
          <Button size="sm" onClick={generateTwin} disabled={loading || !activeFarm} className="gap-1">
            {loading ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />} Refresh
          </Button>
        }
      />

      {!activeFarm ? (
        <EmptyState icon={Radar} title="No farm" description="Complete onboarding to build your farm twin." />
      ) : loading && !twin ? (
        <div className="flex h-64 items-center justify-center">
          <Loader2 className="animate-spin text-primary" size={28} />
        </div>
      ) : !twin ? (
        <EmptyState icon={Radar} title="No twin yet" description="Click Refresh to generate your farm twin." />
      ) : (
        <div className="space-y-6">
          <SectionCard title="Current state" description="Where your farm stands right now">
            <div className="flex items-start gap-3">
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Radar size={18} />
              </span>
              <p className="text-sm text-foreground">{twin.current_state}</p>
            </div>
          </SectionCard>

          <SectionCard title="Projection" description="Estimated outlook for the next 1-4 weeks">
            <div className="flex items-start gap-3">
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-warning/10 text-warning">
                <TrendingUp size={18} />
              </span>
              <p className="text-sm text-foreground">{twin.projection}</p>
            </div>
          </SectionCard>

          <SectionCard title="Personal patterns" description="Insights from your own farm history">
            {twin.pattern_insights.length === 0 ? (
              <p className="text-sm text-muted-foreground">Not enough logged history yet to detect patterns. Keep recording soil tests, crops, and expenses.</p>
            ) : (
              <div className="space-y-3">
                {twin.pattern_insights.map((insight, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-lg border border-border p-3">
                    <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-success/10 text-success">
                      <History size={18} />
                    </span>
                    <p className="text-sm text-foreground">{insight}</p>
                  </div>
                ))}
              </div>
            )}
          </SectionCard>

          <Disclaimer>
            <span className="inline-flex items-center gap-1"><Sparkles size={12} /> Generated by AI from your logged farm data.</span>{' '}
            This is an estimate, not a guarantee — always verify with on-the-ground observation and your local agriculture officer.
            {generatedAt && <> Last updated {generatedAt.toLocaleTimeString()}.</>}
          </Disclaimer>
        </div>
      )}
    </div>
  );
}
